name: Docker GHCR Push Python 3.11
on:
  push:
    branches:
      - master
permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Harden the runner (Audit all outbound calls)
          uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
          with:
            egress-policy: audit

        - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        - name: set up Docker Buildx
          uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
        - name: Login to GitHub Container Registry
          uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: docker-build-push
          uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
          with:
            context: .
            file: ./Dockerfile.3.11
            push: true
            tags: ghcr.io/${{ github.repository }}/base-3-11:latest, ghcr.io/${{ github.repository }}/base-3-11:${{ github.sha }}
            labels: org.opencontainers.image.source = "https://github.com/maa123/rwkvimage"
