name: Docker GHCR Push
on:
  push:
    branches:
      - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: docker-build-push
          uses: docker/build-push-action@v6
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ghcr.io/${{ github.repository }}/base:latest, ghcr.io/${{ github.repository }}/base:${{ github.sha }}
            labels: org.opencontainers.image.source = "https://github.com/maa123/rwkvimage"