name: Docker GHCR Push Python 3.11
on:
  push:
    branches:
      - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: docker-build-push
          uses: docker/build-push-action@v6
          with:
            context: .
            file: ./Dockerfile.3.11
            push: true
            tags: ghcr.io/${{ github.repository }}/base-3-11:latest, ghcr.io/${{ github.repository }}/base-3-11:${{ github.sha }}
            labels: org.opencontainers.image.source = "https://github.com/maa123/rwkvimage"